{% set name = "torchnet" %}
{% set version = "0.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/torchnet-{{ version }}.tar.gz
  sha256: 393e62e0111a49912398a7ddea36c7f737fd22b895e0d718ac05e71a946e3b9b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - six
    - pytorch
    - visdom

test:
  imports:
    - torchnet
    - torchnet.dataset
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytorch/tnt/
  summary: an abstraction to train neural networks
  license: BSD-3-Clause
  license_file: LICENSE